# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  myproject: 'Server/ClientApp.Server.csproj'

steps:
- task: NuGetCommand@2
  displayName: 'Restoring NuGet packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Building for $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) --self-contained -r win-x86)'

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'