# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'macOS-10.15'

variables:
  buildConfiguration: 'Release'
  myproject: 'Server/ClientApp.Server.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Setting up dotnet sdk'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    projects: $(myproject)
    command: 'publish'
    publishWebProjects: true
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) --self-contained -r win-x86'

- task: PublishBuildArtifacts@1
  displayName: 'Publishing Build Artifacts...'
