// <auto-generated />
using System;
using BlazorKidConApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorKidConApp.Server.Migrations
{
    [DbContext(typeof(KidConDbContext))]
    [Migration("20210116125925_TestMig")]
    partial class TestMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClassificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncreasingSide")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IncreasingSide = "debit",
                            Name = "Trading stock"
                        },
                        new
                        {
                            Id = 2L,
                            IncreasingSide = "debit",
                            Name = "Vehicles"
                        },
                        new
                        {
                            Id = 3L,
                            IncreasingSide = "debit",
                            Name = "Equipment"
                        },
                        new
                        {
                            Id = 4L,
                            IncreasingSide = "debit",
                            Name = "Machinery"
                        },
                        new
                        {
                            Id = 5L,
                            IncreasingSide = "debit",
                            Name = "Land and buildings"
                        },
                        new
                        {
                            Id = 6L,
                            IncreasingSide = "debit",
                            Name = "Petty Cash"
                        },
                        new
                        {
                            Id = 7L,
                            IncreasingSide = "debit",
                            Name = "Cash float"
                        },
                        new
                        {
                            Id = 8L,
                            IncreasingSide = "debit",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 9L,
                            IncreasingSide = "debit",
                            Name = "Bank"
                        },
                        new
                        {
                            Id = 10L,
                            IncreasingSide = "debit",
                            Name = "Drawings"
                        },
                        new
                        {
                            Id = 11L,
                            IncreasingSide = "debit",
                            Name = "Salaries"
                        },
                        new
                        {
                            Id = 12L,
                            IncreasingSide = "debit",
                            Name = "Wages"
                        },
                        new
                        {
                            Id = 13L,
                            IncreasingSide = "debit",
                            Name = "Repairs"
                        },
                        new
                        {
                            Id = 14L,
                            IncreasingSide = "debit",
                            Name = "Advertising"
                        },
                        new
                        {
                            Id = 15L,
                            IncreasingSide = "debit",
                            Name = "Telephone"
                        },
                        new
                        {
                            Id = 16L,
                            IncreasingSide = "debit",
                            Name = "Stationery"
                        },
                        new
                        {
                            Id = 17L,
                            IncreasingSide = "debit",
                            Name = "Water and electricity"
                        },
                        new
                        {
                            Id = 18L,
                            IncreasingSide = "debit",
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 19L,
                            IncreasingSide = "debit",
                            Name = "Packing material"
                        },
                        new
                        {
                            Id = 20L,
                            IncreasingSide = "debit",
                            Name = "Fuel"
                        },
                        new
                        {
                            Id = 21L,
                            IncreasingSide = "debit",
                            Name = "Bank charges"
                        },
                        new
                        {
                            Id = 22L,
                            IncreasingSide = "debit",
                            Name = "Consumable goods"
                        },
                        new
                        {
                            Id = 23L,
                            IncreasingSide = "debit",
                            Name = "Interest on loan"
                        },
                        new
                        {
                            Id = 24L,
                            IncreasingSide = "debit",
                            Name = "Interest expense"
                        },
                        new
                        {
                            Id = 25L,
                            IncreasingSide = "debit",
                            Name = "Postage"
                        },
                        new
                        {
                            Id = 26L,
                            IncreasingSide = "debit",
                            Name = "Donations expense"
                        },
                        new
                        {
                            Id = 27L,
                            IncreasingSide = "debit",
                            Name = "Rent expense"
                        },
                        new
                        {
                            Id = 28L,
                            IncreasingSide = "debit",
                            Name = "Cost of Sales"
                        },
                        new
                        {
                            Id = 29L,
                            IncreasingSide = "credit",
                            Name = "Loan"
                        },
                        new
                        {
                            Id = 30L,
                            IncreasingSide = "credit",
                            Name = "Mortgage bond"
                        },
                        new
                        {
                            Id = 31L,
                            IncreasingSide = "credit",
                            Name = "Bank overdraft"
                        },
                        new
                        {
                            Id = 32L,
                            IncreasingSide = "credit",
                            Name = "Creditors Control"
                        },
                        new
                        {
                            Id = 33L,
                            IncreasingSide = "credit",
                            Name = "Current income"
                        },
                        new
                        {
                            Id = 34L,
                            IncreasingSide = "credit",
                            Name = "Rent income"
                        },
                        new
                        {
                            Id = 35L,
                            IncreasingSide = "credit",
                            Name = "Donations income"
                        },
                        new
                        {
                            Id = 36L,
                            IncreasingSide = "credit",
                            Name = "Commission"
                        },
                        new
                        {
                            Id = 37L,
                            IncreasingSide = "credit",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 38L,
                            IncreasingSide = "credit",
                            Name = "Interest income"
                        },
                        new
                        {
                            Id = 39L,
                            IncreasingSide = "credit",
                            Name = "Interest on fixed deposit"
                        },
                        new
                        {
                            Id = 40L,
                            IncreasingSide = "credit",
                            Name = "Capital"
                        });
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Alternative", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativePhrase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Alternatives");
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Business", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Builder",
                            Type = 0
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Plumber",
                            Type = 0
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Electrician",
                            Type = 0
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Accountant",
                            Type = 0
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Painter",
                            Type = 0
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Gardener",
                            Type = 0
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Dancer",
                            Type = 0
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Art Supplier",
                            Type = 1
                        },
                        new
                        {
                            Id = 9L,
                            Description = "New Item Supplier",
                            Type = 1
                        });
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Classification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classifications");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Type = "Asset"
                        },
                        new
                        {
                            Id = 2L,
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 3L,
                            Type = "Drawings"
                        },
                        new
                        {
                            Id = 4L,
                            Type = "Capital"
                        },
                        new
                        {
                            Id = 5L,
                            Type = "Income"
                        },
                        new
                        {
                            Id = 6L,
                            Type = "Liability"
                        });
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Name", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Names");
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Sentence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OtherPartyId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TransactionAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("TransactionPhrase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("OtherPartyId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Account", b =>
                {
                    b.HasOne("BlazorKidConApp.Shared.Models.Classification", "Classification")
                        .WithMany("Accounts")
                        .HasForeignKey("ClassificationId");

                    b.Navigation("Classification");
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Alternative", b =>
                {
                    b.HasOne("BlazorKidConApp.Shared.Models.Account", "Account")
                        .WithMany("Alternatives")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Sentence", b =>
                {
                    b.HasOne("BlazorKidConApp.Shared.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("BlazorKidConApp.Shared.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorKidConApp.Shared.Models.Name", "OtherParty")
                        .WithMany()
                        .HasForeignKey("OtherPartyId");

                    b.HasOne("BlazorKidConApp.Shared.Models.Name", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Account");

                    b.Navigation("Business");

                    b.Navigation("OtherParty");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Account", b =>
                {
                    b.Navigation("Alternatives");
                });

            modelBuilder.Entity("BlazorKidConApp.Shared.Models.Classification", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
